apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30015
  type:
    NodePort
  selector:
    app: guestbook-ui
